import { Plan } from '@/types';

export const PLANS: Plan[] = [
  {
    id: 'basic',
    name: 'Basic',
    price: 49999,
    currency: 'TZS',
    listingsCount: 1,
    featuredDays: 30,
    features: [
      '365-Days Listing Period',
      '1 Business/Public figure listing',
      'Featured For 30 days',
      'In-app chat feature',
      'Reviews Response',
      'Contacts and address',
      'Website URL',
      'Social media profiles',
      'Email support',
    ],
  },
  {
    id: 'standard',
    name: 'Standard',
    price: 99999,
    currency: 'TZS',
    listingsCount: 2,
    featuredDays: 60,
    features: [
      '365-Days Listing Period',
      '2 Business/Public figure listing',
      'Featured For 60 days',
      'In-app chat feature',
      'Reviews Response',
      'Contacts and address',
      'Website URL',
      'Social media profiles',
      'Email support',
    ],
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 149999,
    currency: 'TZS',
    listingsCount: 3,
    featuredDays: 90,
    features: [
      '365-Days Listing Period',
      '3 Business/Public figure listing',
      'Featured For 90 days',
      'In-app chat feature',
      'Reviews Response',
      'Contacts and address',
      'Website URL',
      'Social media profiles',
      'Email & chat support',
    ],
  },
];
